export const articles = [
    {
        articleId: 1,
        title: "Article de Kermi",
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
        content: "",
        urlPdf: "",
        releaseDate: "Tuesday, 02 Oct 2022",
        authors: ["nada", "kermi", "zaineb"]
    },
    {
        articleId: 2,
        title: "Article de Kermi",
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
        content: "",
        urlPdf: "",
        releaseDate: "Tuesday, 02 Oct 2022",
    },
    {
        articleId: 3,
        title: "Article de Kermi",
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
        content: "",
        urlPdf: "",
        releaseDate: "Tuesday, 02 Oct 2022",
    },
    {
        articleId: 4,
        title: "Article de Kermi",
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
        content: "",
        urlPdf: "",
        releaseDate: "Tuesday, 02 Oct 2022",
    },
    {
        articleId: 5,
        title: "Article de Kermi",
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
        content: "",
        urlPdf: "",
        releaseDate: "Tuesday, 02 Oct 2022",
    },
]

// {
//         articleId: 1,
//         title: "Article de Kermi",
//         summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
//         content: "",
//         urlPdf: "",
//         releaseDate: "Tuesday, 02 Oct 2022",
//         authors: ["nada", "kermi", "zaineb"]
//     },
//     {
//         articleId: 2,
//         title: "Article de Kermi",
//         summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
//         content: "",
//         urlPdf: "",
//         releaseDate: "Tuesday, 02 Oct 2022",
//     },
//     {
//         articleId: 3,
//         title: "Article de Kermi",
//         summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
//         content: "",
//         urlPdf: "",
//         releaseDate: "Tuesday, 02 Oct 2022",
//     },
//     {
//         articleId: 4,
//         title: "Article de Kermi",
//         summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
//         content: "",
//         urlPdf: "",
//         releaseDate: "Tuesday, 02 Oct 2022",
//     },
//     {
//         articleId: 5,
//         title: "Article de Kermi",
//         summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ligula urna, hendrerit id nulla in, pulvinar volutpat nulla. Sed est nulla, eleifend sed tempor eu, elementum at tortor. Donec urna sapien, See more...",
//         content: "",
//         urlPdf: "",
//         releaseDate: "Tuesday, 02 Oct 2022",
//     },