import { articles } from "./ArticlesData"
import image from "../assets/image.jpg"

export const moderators = [
    {
        userId: 1,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 120,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Updated",
    },
    {
        userId: 2,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 500,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Deleted",
    },
    {
        userId: 3,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 25,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Deleted",
    },
    {
        userId: 4,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 12,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "updated",
    },
    {
        userId: 5,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 1,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Deleted",
    },
    {
        userId: 6,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 1,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Deleted",
    },
    {
        userId: 6,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 1,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Deleted",
    },
    {
        userId: 6,
        userName: "nadadjg",
        firstName: "Nada",
        familyName: "Djedjig",
        imgUrl: image,
        numberedits: 1,
        lasteditedArticle: articles[0].title,
        editedArticles: articles,
        changes: "Deleted",
    }
] 